const ADD = 'ADD';
const REMOVE = 'REMOVE';
const PRODUCT_QUANTITY = 'PRODUCT_QUANTITY';
const GET_TOTAL = 'GET_TOTAL';
const RESET = 'RESET';
const AMOUNT = 'AMOUNT';

export { ADD, REMOVE, GET_TOTAL, RESET, AMOUNT, PRODUCT_QUANTITY};